import type { Norma } from "./NormasViewModel";

export const NORMAS_BASE: Norma[] = [
  {
    id: "RBAC 25.1309",
    codigo: "25.1309",
    titulo: "Análise de Segurança de Sistemas",
    organizacao: "ANAC",
    categoria: "Instalação",
    subcategoria: "Geral",
    item: "Parafuso",
    tipo: "Pública",
    revisao: "Emenda 09",
    status: "Vigente",
    notas: ["Norma principal de safety."],
    referencias: ["SAE ARP4761"],
    palavrasChave: ["safety", "análise de risco"],
    nomePdf: "rbac-25-1309.pdf",
    urlPdf: "/pdf/rbac-25-1309.pdf",
    imagens: ["/imagem/rbac-25-1309.jpeg"]
  },
  {
    id: "FAR 25.571",
    codigo: "25.571",
    titulo: "Damage Tolerance and Fatigue Evaluation",
    organizacao: "FAA",
    categoria: "Conjunto",
    subcategoria: "União de Peças",
    item: "Soldagem",
    tipo: "Pública",
    revisao: "Amendment 27",
    status: "Vigente",
    notas: [],
    referencias: [],
    palavrasChave: ["fadiga", "tolerância", "dano"],
    nomePdf: "far-25-571.pdf",
    urlPdf: "/pdf/far-25-571.pdf",
    imagens: ["/imagem/far-25-571.jpeg"]
  },
  {
    id: "ISO 9001:2015",
    codigo: "9001",
    titulo: "Quality management systems — Requirements",
    organizacao: "ISO",
    categoria: "Peça",
    subcategoria: "Metálica",
    item: "Usinado",
    tipo: "Pública",
    revisao: "2015",
    status: "Vigente",
    notas: [
      "Requisitos gerais para o sistema de gestão da qualidade nas plantas de manufatura.",
    ],
    referencias: ["ISO 9000:2015"],
    palavrasChave: ["qualidade", "gestão", "requisitos"],
  },
  {
    id: "CS-25",
    codigo: "CS-25",
    titulo: "Certification Specifications for Large Aeroplanes",
    organizacao: "EASA",
    categoria: "Conjunto",
    subcategoria: "Cablagem",
    item: "Conector",
    tipo: "Privada",
    revisao: "Amendment 27",
    status: "Vigente",
    notas: [
      "Especificações essenciais para certificação EASA em aeronaves de grande porte.",
    ],
    referencias: ["FAR 25"],
    palavrasChave: ["certificação", "aeronave grande", "easa"],
  },
];
